#!/usr/bin/env python3

import pychromecast

chromecasts = pychromecast.get_chromecasts()[0]

if len(chromecasts) > 0:
  for cc in chromecasts:
    print("Found '{}' ChromeCast".format(cc.device.friendly_name))
else:
  print("No ChromeCasts found on this network!")
