#!/usr/bin/env python3

import pychromecast

chromecasts = pychromecast.get_chromecasts()

if len(chromecasts) > 0:
  for cc in chromecasts:
    print("Se ha descubierto el ChromeCast'{}'".format(cc.device.friendly_name))
else:
  print("¡No se han descubierto ChromeCast en esta red!")
