# Environment variable names
ENV_YOUTUBE_API_KEY = 'YOUTUBE_API_KEY'

ENV_PLEX_IP_ADDRESS = 'PLEX_IP_ADDRESS'
ENV_PLEX_PORT = 'PLEX_PORT'
ENV_PLEX_SUBTITLE_LANG = 'PLEX_SUBTITLE_LANG'
ENV_PLEX_TOKEN = 'PLEX_TOKEN'
